name: Cherry Pick

on:
  workflow_call:

jobs:
  branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.cherry_pick_branches.outputs.result }}
    steps:
      - name: Check for cherry-pick labels
        id: cherry_pick_branches
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const labels = issue.labels.map(label => label.name);
            console.log(`Labels: ${labels}`);

            const branches = labels.filter(label => label.startsWith('cherry-pick/'))
              .map(label => label.substr(12));
            console.log(`Branches: ${branches}`);

            return branches

  cherry-pick:
    runs-on: ubuntu-latest
    needs: branches
    if: ${{ needs.branches.outputs.branches != '[]' && needs.branches.outputs.branches != '' }}
    strategy:
      matrix:
        branch: ${{ fromJson(needs.branches.outputs.branches) }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.TRUSTIFICATION_BOT_ID }}
          application_private_key: ${{ secrets.TRUSTIFICATION_BOT_KEY }}

      - name: Cherry-pick
        uses: korthout/backport-action@v3
        with:
          github_token: ${{ steps.get_workflow_token.outputs.token }}
          label_pattern: "^cherry\-pick\/([^ ]+)$"
          pull_title: ":seedling: [${target_branch}] ${pull_title}"
